engines:
  rubocop:
    enabled: true
    #checks:
    #	Rubocop/Metrics/ClassLength:
    #  	enabled: false
  golint:
   enabled: true
  eslint:
    enabled: true
    checks:
      max-statements:
        enabled: false
  csslint:
    enabled: true
  phpmd:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
ratings:
  paths:
   - build/**
   - "**.css"
   - "**.inc"
   - "**.js"
   - "**.jsx"
   - "**.module"
   - "**.php"
   - "**.py"
   - "**.rb"
exclude_paths:
 - client/**
 - "build/assets/js/foundation.js"
exclude_fingerprints:
 - c7d8b3b6cf184a3f18ca6516365278b0
