# This file is a template, and might need editing before it works on your project.
# Official docker image.

stages:
  - build
  - dockerize

build-release:
  stage: build
  image: node:8.12
  script:
    - npm install
    - npm run-script build --prod
  artifacts:
    paths:
      - dist/
  only:
    - master
    - tags

build:
  stage: build
  image: node:8.12
  script:
    - npm install
    - npm run-script build --prod
  artifacts:
    paths:
      - dist/
  except:
    - master
    - tags

dockerize-release:
  stage: dockerize
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master
    - tags

dockerize:
  stage: dockerize
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
    - tags
